#!/usr/bin/env python3
"""
Generate api/seed_stations.sql from assets/planck-manifest.json.

One row per addressable page, using the SAME path->code resolution as
build_site.py (first occurrence of a path wins) so the seeded `code` values
match exactly what the injected planck-companion.js reports back. Re-runnable:
emits INSERT ... ON DUPLICATE KEY UPDATE keyed on the unique slug.

Run from the site root after editing the manifest:
    ./.venv/bin/python tools/seed_stations.py     # (plain python3 works too)
Then import api/seed_stations.sql in phpMyAdmin (after schema.sql).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "assets", "planck-manifest.json")
OUT = os.path.join(ROOT, "api", "seed_stations.sql")


def collect(m):
    """path -> (code, chapter, title, type); first write wins (mirrors build_site)."""
    rows = {}
    for ch in m["chapters"]:
        for c in ch.get("components", []):
            p = c["path"]
            if p.endswith(".html"):
                rows.setdefault(p, (c.get("code", ""), ch["n"], c["title"],
                                    c.get("type", "lab")))
        sub = ch.get("subindex")
        if sub and sub.endswith(".html"):
            rows.setdefault(sub, ("", ch["n"], ch["title"] + " — overview", "index"))
    for e in m.get("extras", []):
        p = e["path"]
        if p.endswith(".html"):
            rows.setdefault(p, ("", None, e["title"], "extra"))
    return rows


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    with open(MANIFEST, encoding="utf-8") as f:
        m = json.load(f)
    rows = collect(m)

    lines = [
        "-- Generated by tools/seed_stations.py — do not edit by hand.",
        "-- Run after schema.sql. Re-runnable (upserts on the unique slug).",
        "SET NAMES utf8mb4;",
        "",
    ]
    for path in sorted(rows):
        code, chN, title, typ = rows[path]
        chapter = "NULL" if chN is None else str(chN)
        lines.append(
            "INSERT INTO stations (code, chapter, slug, title, type) VALUES "
            f"({q(code)}, {chapter}, {q(path)}, {q(title)}, {q(typ)}) "
            "ON DUPLICATE KEY UPDATE code=VALUES(code), chapter=VALUES(chapter), "
            "title=VALUES(title), type=VALUES(type);"
        )
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(rows)} stations)")


if __name__ == "__main__":
    main()
